trigger:
  branches:
    include:
      - release/hotfix

    exclude:
      - main

stages:
- stage: DiagnoseHighUsage
  displayName: 'Diagnose High Resource Usage on VM'
  jobs:
  - job: connectToVM
    displayName: 'SSH to VM using key and run diagnostics'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: DownloadSecureFile@1
      displayName: 'Download SSH keys from Az Devops SecureFile'
      name: Ubuntukey           ##Uploaded to Azure Devops -> Project -> Pipeline -> Library
      inputs:
        secureFile: AzUbuntu-key.pem
      
    - script: |
        chmod 600 $(Ubuntukey.secureFilePath)
        ssh -o StrictHostKeyChecking=no -i $(Ubuntukey.secureFilePath) -o GSSAPIAuthentication=no pratul@172.191.228.28
        echo ">>> Conenction successful"
        sudo apt update && sudo apt upgrade -y -p
        echo ">>> Downloading diagnose_usage.sh from GitHub..."
        curl -o ~/diagnose_usage.sh https://github.com/prak96/motadata-assignment/blob/release/hotfix/Linux%20IOSTAT%20automate/diagnose_usage.sh
        
        echo ">>> Setting script permission..."
        chmod +x diagnose_usage.sh

        echo ">>> Running diagnose_usage.sh..."
        bash ~/diagnose_usage.sh

        EOF
      displayName: "Secure SSH conenction to UbuntuVM & execute the SCRIPT"

