trigger:
  branches:
    include:
      - release/hotfix

    exclude:
      - main

stages:
- stage: DiagnoseHighUsage
  displayName: 'Diagnose High Resource Usage on VM'
  jobs:
  - job: connectToVM
    displayName: 'SSH to VM using key and run diagnostics'


    steps:
    - task: DownloadSecureFile@1
      displayName: 'Download SSH keys from Az Devops SecureFile'
      name: Ubuntukey
      inputs:
        secureFile: AzUbuntu-key.pem
      
    - script: |
        chmod 600 $(Ubuntukey.secureFilePath)
        ssh -o StrictHostKeyChecking=no -i $(Ubuntukey.secureFilePath) pratul@20.39.48.127
        echo ">>> Conenction successful"

        echo ">>> Connected to VM. Setting script permission..."

        EOF
      displayName: "Secure SSH conenction to UbuntuVM"

